---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: Disable Domain Firewall
      win_firewall:
        state: disabled
        profiles: 
          - Domain
          - Private
      tags: disable_firewall
    - name: Print message
      debug:
        msg: TASK 1 PASSED
