---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
   - name: Stop and disable firewalld.
     service:
       name: firewalld
       state: stopped
       enabled: False
    - name: Print message
      debug:
        msg: TASK 1 PASS
