---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: powershell to download scripts from internal web server
      win_shell: |
        cd C:\Users\Administrator\Downloads
        Invoke-WebRequest http://172.31.16.247/playbook/join_domain.ps1 -O join_domain.ps1
        C:\Users\Administrator\Downloads\join_domain.ps1
    - name: Print message
      debug:
        msg: TASK 1 PASS AND TASK 2 START
    - name: reboot | Rebooting Server
      win_reboot:
        reboot_timeout_sec: 3600
    - name: Print message
      debug:
        msg: TASK 2 END
