---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: powershell to download scripts from internal web server
      ansible.builtin.get_url:
        script: |
          echo "Hello World"
    - name: Print message
      debug:
        msg: TASK 1 PASS
