---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: powershell to download scripts from internal web server
      ansible.builtin.get_url:
        script: |
          curl http://172.31.16.247/playbook/join_domain.ps1 -O join_domain.ps1
    - name: Print message
      debug:
        msg: TASK 1 PASS
