---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: Downloading scripts from local
      become: false
        ansible.windows.win_copy:
          src: /home/centos/playbook/join_domain.ps1
          dest: C:/Users/Administrator/Downloads/join_domain.ps1
    - name: Print message
      debug:
        msg: TASK 1 PASS
