---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: Downloading scripts from internal web server
      ansible.builtin.get_url:
        url: http://172.31.16.247/playbook/join_domain.ps1
        dest: C:\Users\Administrator\Downloads
        mode: '0440'
    - name: Print message
      debug:
        msg: TASK 1 PASS
