---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: powershell to download scripts from internal web server
      win_shell: |
        cd C:\Users\Administrator\Downloads
        Invoke-WebRequest http://172.31.16.247/playbook/join_domain.ps1 -O join_domain.ps1
    - name: Print message
      debug:
        msg: TASK 1 END
