---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: powershell to download scripts from internal web server
      win_shell:
        C:\\Users\\Administrator\\Downloads\\join_domain.ps1
    - name: Print message
      debug:
        msg: TASK 1 END 
    - name: End powershell
      win_shell: |
        echo "TASK END"
