---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: Execute join domain script
      win_shell:
        C:\Users\Administrator\Downloads\join_domain.ps1
    - name: Print message
      debug:
        msg: TASK 1 END 
    - name: End powershell
      win_shell: |
        echo "TASK END"
