---
- hosts: all
  gather_facts: no
  tasks:
  - win_domain_membership:
      dns_domain_name: ad.attackdefense.com
      hostname: '{{ inventory_hostname }}'
      domain_admin_user: Administrator@ad.attackdefense.com
      domain_admin_password: Aa@20070173
      domain_ou_path: "OU=Windows,OU=Servers,DC=yourdomain,DC=local"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
