---
- hosts: all
  gather_facts: false
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: ad.attackdefense.com
      hostname: EC2AMAZ-4V2UJES
      domain_admin_user: Administrator@ad.attackdefense.com
      domain_admin_password: Aa@20070173
      domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
      state: domain
    register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required
