---
- hosts: all
  gather_facts: false
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: ad.attackdefense.com
      hostname: "{{inventory_hostname}}"
      domain_admin_user: 
      domain_admin_password: 
      domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
      state: domain
    register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required
