---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: STARTING TASK 1
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          $domain = attackdefense.local
          $password = uFa^J031*96H
          $username = localuser01
          $credential = New-Object System.Management.Automation.PSCredential($username,$password)
          Add-Computer -DomainName $domain -Credential $credential
    - name: Print message
      debug:
        msg: TASK 1 PASS
