---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: STARTING TASK 1
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          $domain = 
          $password = 
          $username = 
          $credential = New-Object System.Management.Automation.PSCredential($username,$password)
          Add-Computer -DomainName $domain -Credential $credential
    - name: Print message
      debug:
        msg: TASK 1 PASS AND STARTING TASK 2
    - name: reboot | Rebooting Server
      win_reboot:
        reboot_timeout_sec: 3600
      when: >
        _windows_dns_server['restart_needed'] is defined and
        _windows_dns_server['restart_needed']
    - name: Print message
      debug:
        msg: TASK 2 PASS
