---
- hosts: all
  gather_facts: false
  tasks:
    - name: Copy sysmon config
      win_get_url:
        url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
        dest: C:\Users\Administrator\Downloads\Sysmonconfig-export.xml
    - name: check sysmon service
      win_service:
        name: sysmon64
      register: result
      failed_when: result is not defined
      ignore_errors: yes
    - name: Run sysmon
      win_command: "C:\Users\Administrator\Downloads\Sysmon\Sysmon64.exe -accepteula -i C:\Users\Administrator\Downloads\Sysmonconfig-export.xml"
      args:
        chdir: C:\Users\Administrator\Downloads\Sysmon
