---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START TASK 1
    - name: download sysmon
      win_get_url:
        url: https://download.sysinternals.com/files/Sysmon.zip
        dest: C:\Users\Administrator\Downloads\Sysmon.zip
    - name: Print message
      debug:
        msg: TASK 1 END
    - name: Print message
      debug:
        msg: START TASK 2
    - name: unzip sysmon package
      win_unzip:
        src: C:\Users\Administrator\Downloads\Sysmon.zip
        dest: C:\Users\Administrator\Downloads\Sysmon
    - name: Print message
      debug:
        msg: TASK 2 END
