---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START TASK 1
    - name: download sysmon
      win_get_url:
        url: https://download.sysinternals.com/files/Sysmon.zip
        dest: C:\Users\Administrator\Downloads\Sysmon.zip
    - name: Print message
      debug:
        msg: TASK 1 END
    - name: Print message
      debug:
        msg: START TASK 2
    - name: Get sysmon config
      win_get_url:
        url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
        dest: C:\Users\Administrator\Downloads\Sysmonconfig-export.xml
    - name: Print message
      debug:
        msg: TASK 2 END

