---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START TASK 1
    - name: download sysmon
      win_get_url:
        url: https://download.sysinternals.com/files/Sysmon.zip
        dest: C:\Users\Administrator\Downloads\Sysmon.zip
    - name: Print message
      debug:
        msg: TASK 1 END
    - name: Print message
      debug:
        msg: START TASK 2
    - name: Get sysmon config
      win_get_url:
        url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
        dest: C:\Users\Administrator\Downloads\Sysmonconfig-export.xml
    - name: Print message
      debug:
        msg: TASK 2 END
    - name: Print message
      debug:
        msg: TASK 3 START
    - name: Unzip sysmon file; copy sysmonconfig-export.xml file into the unzipped sysmon file directory and perform installation
      win_shell: |
        powershell.exe
        cd C:\Users\Administrator\Downloads
        Expand-Archive -Path C:\Users\Administrator\Downloads\Sysmon.zip -DestinationPath C:\Users\Administrator\Downloads\Sysmon
        Copy-Item -Path .\Sysmonconfig-export.xml -Destination C:\Users\Administrator\Downloads\Sysmon\Sysmonconfig-export.xml 
        C:\Users\Administrator\Downloads\Sysmon\Sysmon64.exe -accepteula -i C:\Users\Administrator\Downloads\Sysmon\Sysmonconfig-export.xml 
    - name: Print message
      debug:
        msg: TASK 4 END
