---
- hosts: all
  gather_facts: false
  tasks:
    - name: Get sysmon zip
      win_get_url:
        url: https://download.sysinternals.com/files/Sysmon.zip
        dest: C:\Users\Administrator\Downloads\Sysmon.zip
    - name: Unzip sysmon
      win_unzip:
        src: C:\Users\Administrator\Downloads\Sysmon.zip
        dest: C:\Users\Administrator\Downloads\Sysmonz
    - name: Copy sysmon config
      win_get_url:
        url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
        dest: C:\Users\Administrator\Downloads\Sysmonconfig-export.xml
    - name: check sysmon service
      win_service:
        name: sysmon64
      register: result
      failed_when: result is not defined
      ignore_errors: yes
    - name: Run sysmon
      win_command: "{{ sysmon_install_location }}\\sysmon64.exe -accepteula -i {{ sysmon_install_location }}\\sysmonconfig-export.xml"
      args:
        chdir: "{{ sysmon_install_location }}"
      when: result.state is not defined or result.name is not defined
