---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: FLAG 1
    - name: Installing windows DNS Server
      win_feature:
        name: DNS
        state: present
        include_management_tools: yes
        include_sub_features: yes
      register: _windows_dns_server
