---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
  - name: Reboot if installing Web-Server feature requires it
      ansible.windows.win_reboot:
      when: win_feature.reboot_required
