---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print message
      debug:
        msg: START 1
    - name: Installing windows DNS Server
      win_feature:
        name: DNS
        state: present
        include_management_tools: yes
        include_sub_features: yes
      register: _windows_dns_server
    - name: Print message
      debug:
        msg: TASK 1 PASS
    - name: reboot | Rebooting Server
      win_reboot:
        reboot_timeout_sec: 3600
      when: >
        _windows_dns_server['restart_needed'] is defined and
        _windows_dns_server['restart_needed']
    - name: Print message
      debug:
        msg: TASK 2 PASS 
    - name: features | Installing RSAT AD Admin Center
      win_feature:
        name: RSAT-AD-AdminCenter
        state: present
    - name: Print message
      debug:
        msg: TASK 3 PASS
    - name: features | Installing AD Domain Services
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present
    - name: Print message
      debug:
        msg: TASK 4 PASS
